/**
 * Features table: Feature Group, Feature / Function, Initiative Type, End User Category,
 * Monetization Model, Focus Timeframe, Priority (1–3), Development (UI / Data / Algorithm scope).
 * Empty featureGroup means same group as previous row.
 */
const _featuresRowsRaw = [
  { featureGroup: 'Admin Controls', feature: 'Account user/email transfer – updates propagate to cloud and thermostat', initiativeType: 'New Function Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Multi-user role management (Admin vs Guest)', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Activation code via email with SMS OTP option', initiativeType: 'New Function Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Face ID login support', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI only' },
  { featureGroup: '', feature: 'Fingerprint authentication', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI only' },
  { featureGroup: '', feature: 'Password update prompts for web and native app when biometric auth not enabled', initiativeType: 'New Function Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI only' },
  { featureGroup: '', feature: 'Thermostat brightness control', initiativeType: 'New Technical Integration', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data' },
  { featureGroup: 'Performance Analytics', feature: 'Embed analytics into all features to measure delivered value', initiativeType: 'New Feature Introduction', endUserCategory: 'Intelligence & Automation', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Feature impact analytics combined with qualitative feedback', initiativeType: 'New Feature Introduction', endUserCategory: 'Intelligence & Automation', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Monitor feature adoption and engagement (usage frequency, conversion rates)', initiativeType: 'New Feature Introduction', endUserCategory: 'Intelligence & Automation', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Data‑driven roadmap iteration based on analytics', initiativeType: 'New Feature Introduction', endUserCategory: 'Intelligence & Automation', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: 'User Experience', feature: 'In-app contextual guidance (tooltips, walkthroughs)', initiativeType: 'New Feature Introduction', endUserCategory: 'Ease of Use & Accessibility', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI only' },
  { featureGroup: '', feature: 'Navigation ease (buttons, fonts, usability, speed, back buttons, skins)', initiativeType: 'New Feature Introduction', endUserCategory: 'Ease of Use & Accessibility', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI only' },
  { featureGroup: '', feature: 'Hide unavailable features', initiativeType: 'New Feature Introduction', endUserCategory: 'Ease of Use & Accessibility', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI only' },
  { featureGroup: '', feature: 'Iconography (fan running, away mode, fuel source, system mode)', initiativeType: 'New Feature Introduction', endUserCategory: 'Ease of Use & Accessibility', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI only' },
  { featureGroup: '', feature: 'Notify and explain abnormal activity to users', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Error codes explained in layman\'s terms', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'AI chat capability: Natural language, contextual navigation', initiativeType: 'New Function Introduction', endUserCategory: 'Intelligence & Automation', monetizationModel: 'Basic (Free)', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'AI chat capability: Proactive suggestions', initiativeType: 'New Function Introduction', endUserCategory: 'Intelligence & Automation', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Ratings pop‑up every 3 months with "Do not show again" option', initiativeType: 'New Feature Introduction', endUserCategory: 'Engagement & Personalization', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data' },
  { featureGroup: '', feature: 'Ability for users to submit feature requests intuitively', initiativeType: 'New Feature Introduction', endUserCategory: 'Engagement & Personalization', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data' },
  { featureGroup: '', feature: 'Animated blue butterfly interaction', initiativeType: 'New Feature Introduction', endUserCategory: 'Engagement & Personalization', monetizationModel: 'Basic (Free)', priority: 3, development: 'UI only' },
  { featureGroup: '', feature: 'Visual avatar for AI assistant', initiativeType: 'New Feature Introduction', endUserCategory: 'Engagement & Personalization', monetizationModel: 'Basic (Free)', priority: 3, development: 'UI only' },
  { featureGroup: '', feature: 'Gamified experience (earn butterflies, unlock rewards)', initiativeType: 'New Feature Introduction', endUserCategory: 'Engagement & Personalization', monetizationModel: 'Basic (Free)', priority: 3, development: 'UI + Data' },
  { featureGroup: '', feature: 'Seasonal UI themes', initiativeType: 'New Feature Introduction', endUserCategory: 'Engagement & Personalization', monetizationModel: 'Basic (Free)', priority: 3, development: 'UI only' },
  { featureGroup: '', feature: 'Air quality feedback indicator', initiativeType: 'New Feature Introduction', endUserCategory: 'Comfort & Health', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data' },
  { featureGroup: '', feature: 'Energy‑efficient mode indicator (Nest‑like green leaf)', initiativeType: 'New Feature Introduction', endUserCategory: 'Energy & Sustainability', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data' },
  { featureGroup: 'Support and Maintenance', feature: 'Browsers (for web app when launched): Chrome, Firefox, Safari, Edge', initiativeType: 'Sustaining', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI only' },
  { featureGroup: '', feature: 'Mobile OS Version: iOS, Android', initiativeType: 'Sustaining', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI only' },
  { featureGroup: '', feature: 'Devices: iOS, Android', initiativeType: 'Sustaining', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI only' },
  { featureGroup: 'Remote Control', feature: 'Lock and unlock thermostat', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Remote system performance monitoring', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Adjust temperature remotely', initiativeType: 'New Feature Introduction', endUserCategory: 'Comfort & Health', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Schedule setup and modification (daily, seasonal, vacation)', initiativeType: 'New Feature Introduction', endUserCategory: 'Comfort & Health', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Allow scheduling in Cool‑only or Heat‑only mode', initiativeType: 'New Feature Introduction', endUserCategory: 'Comfort & Health', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Resume / override schedule behavior', initiativeType: 'New Feature Introduction', endUserCategory: 'Comfort & Health', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Fan speed control for mini‑splits (auto for unitary systems)', initiativeType: 'New Function Introduction', endUserCategory: 'Comfort & Health', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data' },
  { featureGroup: '', feature: 'Fan circulation scheduling (hours per day)', initiativeType: 'New Feature Introduction', endUserCategory: 'Comfort & Health', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data' },
  { featureGroup: '', feature: 'Increase scheduling limit beyond 4/day', initiativeType: 'New Feature Introduction', endUserCategory: 'Ease of Use & Accessibility', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data' },
  { featureGroup: 'Smart Home & Device Integration', feature: 'Alexa integration', initiativeType: 'New Technical Integration', endUserCategory: 'Ease of Use & Accessibility', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Google Assistant integration', initiativeType: 'New Technical Integration', endUserCategory: 'Ease of Use & Accessibility', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Apple HomeKit integration', initiativeType: 'New Technical Integration', endUserCategory: 'Ease of Use & Accessibility', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Celsius temperature support (Canada)', initiativeType: 'New Feature Introduction', endUserCategory: 'Ease of Use & Accessibility', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI only' },
  { featureGroup: '', feature: 'Smartwatch support', initiativeType: 'New Feature Introduction', endUserCategory: 'Ease of Use & Accessibility', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI only' },
  { featureGroup: '', feature: 'Tablet support', initiativeType: 'New Feature Introduction', endUserCategory: 'Ease of Use & Accessibility', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI only' },
  { featureGroup: '', feature: 'Desktop web access', initiativeType: 'New Function Introduction', endUserCategory: 'Ease of Use & Accessibility', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data' },
  { featureGroup: '', feature: 'Branded voice assistant: Voice command input & Spoken responses', initiativeType: 'New Feature Introduction', endUserCategory: 'Intelligence & Automation', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Branded voice assistant: Proactive voice driven intelligence & actions', initiativeType: 'New Function Introduction', endUserCategory: 'Intelligence & Automation', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Security Sync – HVAC off when doors/windows open or system armed', initiativeType: 'New Function Introduction', endUserCategory: 'Energy & Sustainability', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Sleep Sync – integrate sleep trackers for optimal temperature', initiativeType: 'New Function Introduction', endUserCategory: 'Comfort & Health', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Support RAQA product line', initiativeType: 'New Product Integration', endUserCategory: 'Ease of Use & Accessibility', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'IAQ product integration', initiativeType: 'New Technical Integration', endUserCategory: 'Comfort & Health', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data' },
  { featureGroup: 'Home Energy Reports', feature: 'Temperature & humidity trend views (real‑time, daily, weekly, monthly)', initiativeType: 'New Feature Introduction', endUserCategory: 'Comfort & Health', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'System mode visibility (current & historical):\na) Equipment usage tracking (heat pump, furnace, aux heat)\nb) Outdoor temperature & humidity\nc) Indoor temperature & humidity\nd) System setting (cool / heat)\ne) Fan status (on/off)', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Filter change alerts (time‑based)', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Filter change alerts (runtime‑based)', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Service and tune‑up recommendations', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Historical energy comparisons (MoM, YoY – gas & electric)', initiativeType: 'New Feature Introduction', endUserCategory: 'Energy & Sustainability', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data' },
  { featureGroup: '', feature: 'Deep analysis in energy comparisons (i.e. weather impact)', initiativeType: 'New Feature Introduction', endUserCategory: 'Energy & Sustainability', monetizationModel: '', priority: 2, development: 'UI + Data' },
  { featureGroup: '', feature: 'Runtime analysis (inverter vs non‑inverter simulation)', initiativeType: 'New Function Introduction', endUserCategory: 'Energy & Sustainability', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Peer home energy comparison', initiativeType: 'New Function Introduction', endUserCategory: 'Energy & Sustainability', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Energy savings vs. non‑heat‑pump systems', initiativeType: 'New Function Introduction', endUserCategory: 'Energy & Sustainability', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Actionable savings recommendations (cost & carbon):\na) Optimal thermostat settings based on weather, pricing, rate plans\nb) Optimal dual‑fuel switchover temperature', initiativeType: 'New Function Introduction', endUserCategory: 'Energy & Sustainability', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Solar and battery integration insights', initiativeType: 'New Function Introduction', endUserCategory: 'Energy & Sustainability', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Low‑cost efficiency measures (LEDs, etc.)', initiativeType: 'New Function Introduction', endUserCategory: 'Energy & Sustainability', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data + Algorithm' },
  { featureGroup: 'Adaptive learning', feature: 'Seasonal adjustments for peak energy periods', initiativeType: 'New Function Introduction', endUserCategory: 'Energy & Sustainability', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Time‑of‑Use optimization', initiativeType: 'New Function Introduction', endUserCategory: 'Energy & Sustainability', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Predictive preconditioning using weather and calendar', initiativeType: 'New Function Introduction', endUserCategory: 'Intelligence & Automation', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Smart routines based on behavior', initiativeType: 'New Function Introduction', endUserCategory: 'Intelligence & Automation', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Automatic humidification adjustment', initiativeType: 'New Function Introduction', endUserCategory: 'Comfort & Health', monetizationModel: 'Paid', priority: 2, development: 'UI + Data + Algorithm' },
  { featureGroup: 'Away & Geofencing', feature: 'Automatic energy‑saving mode when away', initiativeType: 'New Feature Introduction', endUserCategory: 'Energy & Sustainability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Multi‑user presence support', initiativeType: 'New Feature Introduction', endUserCategory: 'Intelligence & Automation', monetizationModel: 'Paid', priority: 2, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Handle connectivity limitations (Wi‑Fi / cellular)', initiativeType: 'Sustaining', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'OS background app constraints (iOS / Android)', initiativeType: 'Sustaining', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: 'Room & Zone Intelligence', feature: 'Room RHT sensors: Average temperature across RHTs', initiativeType: 'New Feature Introduction', endUserCategory: 'Comfort & Health', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Room RHT sensors: Per‑room temperature auto control via RHT', initiativeType: 'New Feature Introduction', endUserCategory: 'Comfort & Health', monetizationModel: 'Paid', priority: 2, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Zoned comfort control: Dynamic damper control', initiativeType: 'New Feature Introduction', endUserCategory: 'Comfort & Health', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI + Data' },
  { featureGroup: '', feature: 'Pet Mode temperature auto control', initiativeType: 'New Feature Introduction', endUserCategory: 'Comfort & Health', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Zoned comfort auto control: Occupancy‑based zoning', initiativeType: 'New Function Introduction', endUserCategory: 'Energy & Sustainability', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: 'Demand Response', feature: 'Utility demand response participation during peak events', initiativeType: 'New Interoperability Capability', endUserCategory: 'Energy & Sustainability', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: 'Smart Maintenance & Diagnostics', feature: 'Predictive failure detection and service suggestions', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Self‑diagnosis (usage and system health)', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Paid', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Automated issue reporting to homeowner and dealer', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Paid', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Filter health monitoring (includes filter replacement plan)', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Paid', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Heating / cooling anomaly detection', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: 'Mood & Activity‑Based Control', feature: 'Mood detection via wearables or voice tone', initiativeType: 'New Function Introduction', endUserCategory: 'Intelligence & Automation', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: '', feature: 'Activity‑based settings (party, workout, etc.)', initiativeType: 'New Function Introduction', endUserCategory: 'Intelligence & Automation', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: 'Solar & System Protection', feature: 'Solar Sync – HVAC optimization based on solar production', initiativeType: 'New Function Introduction', endUserCategory: 'Energy & Sustainability', monetizationModel: 'Paid', priority: 3, development: 'UI + Data + Algorithm' },
  { featureGroup: 'Product & Warranty', feature: 'Automatic warranty registration', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Access to purchased products', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: '', feature: 'Access to warranty certificates', initiativeType: 'New Feature Introduction', endUserCategory: 'Trust, Security & Reliability', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI + Data' },
  { featureGroup: 'Customization & Accessibility', feature: 'Custom skins and themes', initiativeType: 'New Feature Introduction', endUserCategory: 'Engagement & Personalization', monetizationModel: 'Basic (Free)', priority: 2, development: 'UI only' },
  { featureGroup: '', feature: 'Multi‑language app support', initiativeType: 'New Feature Introduction', endUserCategory: 'Ease of Use & Accessibility', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI only' },
  { featureGroup: '', feature: 'Accessibility mode for visually impaired and elderly users', initiativeType: 'New Feature Introduction', endUserCategory: 'Ease of Use & Accessibility', monetizationModel: 'Basic (Free)', priority: 1, development: 'UI only' },
]

const SKYPORT_FEATURE_FOCUS_TIMEFRAMES = [
  'Q4 FY26',
  'Q2 FY26',
  'Q1 FY26',
  'Q1 FY26',
  'Q1 FY26',
  'Q1 FY26',
  'Q3 FY26',
  'Q2 FY26',
  'Q2 FY26',
  'Q2 FY26',
  'Q2 FY26',
  'Q1 FY26',
  'Q1 FY26',
  'Q1 FY26',
  'Q1 FY26',
  'Q1 FY26',
  'Q1 FY26',
  'FY27+',
  'FY27+',
  'Q1 FY26',
  'Q1 FY26',
  'Q1 FY26',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'Q3 FY26',
  'FY26 (ongoing)',
  'FY26 (ongoing)',
  'FY26 (ongoing)',
  'Q3 FY26',
  'Q3 FY26',
  'Q3 FY26',
  'Q3 FY26',
  'Q3 FY26',
  'Q3 FY26',
  'Q3 FY26',
  'Q4 FY26',
  'Q3 FY26',
  'Q1 FY26',
  'Q1 FY26',
  'FY27+',
  'Q2 FY26',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'Q4 FY26',
  'Q4 FY26',
  'Q4 FY26',
  'Q4 FY26',
  'Q4 FY26',
  'Q3 FY26',
  'Q4 FY26',
  'Q4 FY26',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'Q4 FY26',
  'FY27+',
  'Q3 FY26',
  'Q3 FY26',
  'Q3 FY26',
  'Q3 FY26',
  'Q3 FY26',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'Q4 FY26',
  'Q4 FY26',
  'Q4 FY26',
  'FY27+',
  'FY27+',
  'FY27+',
  'FY27+',
  'Q4 FY26',
  'Q4 FY26',
  'Q4 FY26',
  'FY27+',
  'FY27+',
  'FY27+',
]

export const featuresRows = _featuresRowsRaw.map((row, i) => ({
  ...row,
  focusTimeframe: SKYPORT_FEATURE_FOCUS_TIMEFRAMES[i] ?? '—',
}))

/** Blue = done; Orange = partially done. Match by exact feature text. */
export const featuresDone = new Set([
  'Face ID login support',
  'Fingerprint authentication',
  'Mobile OS Version: iOS, Android',
  'Devices: iOS, Android',
  'Adjust temperature remotely',
  'Alexa integration',
  'Google Assistant integration',
  'Automatic energy‑saving mode when away',
])

export const featuresPartial = new Set([
  'Account user/email transfer – updates propagate to cloud and thermostat',
])
